preload = ["./reflect-metadata-import.ts"]

[test]
preload = ["./reflect-metadata-import.ts"]
coverage = true
coverageReporter  = ["text", "lcov"]  # default ["text"]
coverageDir = "coverage"  # default "coverage"
